name: Auto Merge Develop to Main

on:
  push:
    branches:
      - develop

jobs:
  auto-merge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Ensure full history

      - name: Configure Git
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      - name: Fetch develop and main
        run: |
          git fetch origin develop
          git fetch origin main

      - name: Merge develop into main
        env:
          GH_TOKEN: ${{ secrets.Laravel_laracast_learning_token  }}
        run: |
          git checkout main
          git merge origin/develop --no-ff --no-edit
          git push https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/${{ github.repository }} HEAD:main